### ISSUE TITLE
[Bug]: NoSuchElementException: Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by RyosukeDTomita** [RyosukeDTomita/ocn_daily_login_aws_lambda#4]
### What happened?

When run this script in aws lambda, NoSuchElementException occured.

### Version

1.0.2 (Default)

### Relevant log output

```shell
[ERROR] NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/div/div[3]/a/img"}
(Session info: headless chrome=69.0.3497.81)
(Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.14.255-311-248.529.amzn2.x86_64 x86_64)
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 36, in lambda_handler
    _get_daily_point(driver)
  File "/var/task/lambda_function.py", line 102, in _get_daily_point
    point_button = driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/div/div[3]/a/img')
  File "/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
END RequestId: 8c4dc65a-61c7-424c-9936-ca3ee6c216b9
REPORT RequestId: 8c4dc65a-61c7-424c-9936-ca3ee6c216b9	Duration: 23963.35 ms	Billed Duration: 23964 ms	Memory Size: 3007 MB	Max Memory Used: 454 MB	Init Duration: 342.66 ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyosukeDTomita** [comment]
https://github.com/RyosukeDTomita/ocn_daily_login_aws_lambda/commit/b11f72a56ae49e4d625b9ae743e1b4423c75cf51
解決。

**Comment by RyosukeDTomita** [comment]
消し忘れてたのでクローズ
